ubuntu@ip-172-31-7-25:~/simple-webapp-flask$ cat Dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt install default-jre
COPY hello.java /opt/
ENTRYPOINT=/opt/hello.java  --host=0.0.0.0 --port=8080
